# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed

# For beginners, we downscale velocity and acceleration limits.
# You can always specify higher scaling factors (<= 1.0) in your motion requests.  # Increase the values below to 1.0 to always move at maximum speed.
default_velocity_scaling_factor: 0.1
default_acceleration_scaling_factor: 0.1

# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  arm_1_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_2_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_3_joint:
    has_velocity_limits: true
    max_velocity: 2.3500000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  arm_4_joint:
    has_velocity_limits: true
    max_velocity: 2.3500000000000001
    has_acceleration_limits: false
    max_acceleration: 0
  arm_5_joint:
    has_velocity_limits: true
    max_velocity: 1.95
    has_acceleration_limits: false
    max_acceleration: 0
  arm_6_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  arm_7_joint:
    has_velocity_limits: true
    max_velocity: 1.76
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_left_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.050000000000000003
    has_acceleration_limits: false
    max_acceleration: 0
  gripper_right_finger_joint:
    has_velocity_limits: true
    max_velocity: 0.050000000000000003
    has_acceleration_limits: false
    max_acceleration: 0
  torso_lift_joint:
    has_velocity_limits: true
    max_velocity: 0.070000000000000007
    has_acceleration_limits: false
    max_acceleration: 0